<?xml version='1.0'  encoding="UTF-8"?>
<!DOCTYPE myBooks [
        <!ELEMENT myBooks (book)*>
        <!ELEMENT book (id|title|author|page_number)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT author (last_name|first_name|patronymic)*>
        <!ELEMENT last_name (#PCDATA)>
        <!ELEMENT first_name (#PCDATA)>
        <!ELEMENT patronymic (#PCDATA)>
        <!ELEMENT page_number (#PCDATA)>
        ]>
<myBooks>
<book>
<id>
6
</id>
<title>
Война и Мир
</title>
<author>
<last_name>
Толстой
</last_name>
<first_name>
Лев
</first_name>
<patronymic>
Николаевич
</patronymic>
</author>
<page_number>
789
</page_number>
</book>
<book>
<id>
15
</id>
<title>
Базы данных
</title>
<author>
<last_name>
Фио
</last_name>
<first_name>
Имя
</first_name>
<patronymic>

</patronymic>
</author>
<page_number>
0
</page_number>
</book>
</myBooks>